// Bismillah Clinic — Complete Kent Repertory Data
// 10 Chapters | 144+ Rubrics | 42 Remedies

var REPERTORY_DATA = {
  "mind": {"ur":"دماغ / ذہن","en":"Mind","roman":"Dimagh","rubrics":{
    "mind_anger":{"ur":"غصہ","en":"Anger, irascibility","roman":"Ghussa","remedies":[{"rem":"nux_vomica","g":3},{"rem":"chamomilla","g":3},{"rem":"bryonia","g":2},{"rem":"staphysagria","g":3},{"rem":"aconite","g":2},{"rem":"ignatia","g":2},{"rem":"natrum_mur","g":2},{"rem":"lycopodium","g":2}]},
    "mind_anger_silent":{"ur":"غصہ، دبایا ہوا","en":"Anger, suppressed","roman":"Ghussa, dabaya","remedies":[{"rem":"staphysagria","g":3},{"rem":"ignatia","g":3},{"rem":"natrum_mur","g":2},{"rem":"aurum_met","g":2},{"rem":"colocynth","g":2}]},
    "mind_anxiety":{"ur":"بے چینی","en":"Anxiety","roman":"Bechaini","remedies":[{"rem":"aconite","g":3},{"rem":"arsenicum","g":3},{"rem":"phosphorus","g":2},{"rem":"pulsatilla","g":2},{"rem":"gelsemium","g":2},{"rem":"argentum_nit","g":2},{"rem":"ignatia","g":2}]},
    "mind_anxiety_health":{"ur":"بے چینی، صحت کی","en":"Anxiety, about health","roman":"Bechaini, sehat","remedies":[{"rem":"arsenicum","g":3},{"rem":"phosphorus","g":3},{"rem":"calcarea_carb","g":2},{"rem":"nitric_acid","g":2},{"rem":"kali_carb","g":2}]},
    "mind_anxiety_future":{"ur":"بے چینی، مستقبل","en":"Anxiety, future","roman":"Bechaini, mustaqbil","remedies":[{"rem":"argentum_nit","g":3},{"rem":"gelsemium","g":2},{"rem":"phosphorus","g":2},{"rem":"calcarea_carb","g":2}]},
    "mind_sadness":{"ur":"اداسی","en":"Sadness, depression","roman":"Udasi","remedies":[{"rem":"ignatia","g":3},{"rem":"natrum_mur","g":3},{"rem":"pulsatilla","g":2},{"rem":"aurum_met","g":3},{"rem":"sepia","g":2},{"rem":"lachesis","g":2}]},
    "mind_weeping":{"ur":"رونا","en":"Weeping","roman":"Rona","remedies":[{"rem":"pulsatilla","g":3},{"rem":"ignatia","g":3},{"rem":"natrum_mur","g":2},{"rem":"sepia","g":2},{"rem":"lilium_tig","g":2}]},
    "mind_weeping_console_agg":{"ur":"رونا، تسلی سے بڑھے","en":"Weeping, consolation agg","roman":"Rona, tasalli se","remedies":[{"rem":"natrum_mur","g":3},{"rem":"ignatia","g":2},{"rem":"sepia","g":3}]},
    "mind_weeping_console_amel":{"ur":"رونا، تسلی سے آرام","en":"Weeping, consolation amel","roman":"Rona, tasalli se aaram","remedies":[{"rem":"pulsatilla","g":3},{"rem":"phosphorus","g":2},{"rem":"calcarea_carb","g":2}]},
    "mind_fear":{"ur":"خوف","en":"Fear","roman":"Khauf","remedies":[{"rem":"aconite","g":3},{"rem":"arsenicum","g":2},{"rem":"phosphorus","g":2},{"rem":"gelsemium","g":2},{"rem":"opium","g":2},{"rem":"stramonium","g":2}]},
    "mind_fear_death":{"ur":"خوف، موت کا","en":"Fear, of death","roman":"Khauf, maut","remedies":[{"rem":"aconite","g":3},{"rem":"arsenicum","g":3},{"rem":"phosphorus","g":2},{"rem":"gelsemium","g":2},{"rem":"lachesis","g":2}]},
    "mind_fear_crowd":{"ur":"خوف، ہجوم سے","en":"Fear, crowd","roman":"Khauf, hujoom","remedies":[{"rem":"lycopodium","g":3},{"rem":"gelsemium","g":2},{"rem":"pulsatilla","g":2},{"rem":"argentum_nit","g":2}]},
    "mind_restlessness":{"ur":"بے قراری","en":"Restlessness","roman":"Be-qarari","remedies":[{"rem":"arsenicum","g":3},{"rem":"aconite","g":3},{"rem":"rhus_tox","g":3},{"rem":"chamomilla","g":2},{"rem":"ferrum_met","g":2}]},
    "mind_company_aversion":{"ur":"تنہائی پسند","en":"Company, aversion","roman":"Tanhai","remedies":[{"rem":"natrum_mur","g":3},{"rem":"sepia","g":3},{"rem":"ignatia","g":2},{"rem":"gelsemium","g":2},{"rem":"aurum_met","g":2}]},
    "mind_company_desires":{"ur":"صحبت کی خواہش","en":"Company, desires","roman":"Sohbat","remedies":[{"rem":"phosphorus","g":3},{"rem":"arsenicum","g":3},{"rem":"pulsatilla","g":2},{"rem":"hyoscyamus","g":2},{"rem":"lachesis","g":2}]},
    "mind_indifference":{"ur":"بے حسی","en":"Indifference, apathy","roman":"Be-hissi","remedies":[{"rem":"sepia","g":3},{"rem":"phosphorus","g":2},{"rem":"natrum_mur","g":2},{"rem":"helliborus","g":2}]},
    "mind_hurry":{"ur":"جلد بازی","en":"Hurry, hastiness","roman":"Jald baazi","remedies":[{"rem":"argentum_nit","g":3},{"rem":"lilium_tig","g":2},{"rem":"medorrhinum","g":2},{"rem":"sulphur","g":2}]},
    "mind_confusion":{"ur":"الجھن، ذہنی","en":"Confusion","roman":"Uljhan","remedies":[{"rem":"baptisia","g":3},{"rem":"nux_vomica","g":2},{"rem":"gelsemium","g":2},{"rem":"phosphorus","g":2},{"rem":"rhus_tox","g":2}]}
  }},
  "head": {"ur":"سر","en":"Head","roman":"Sar","rubrics":{
    "head_pain":{"ur":"سر درد","en":"Headache","roman":"Sar dard","remedies":[{"rem":"belladonna","g":3},{"rem":"bryonia","g":3},{"rem":"nux_vomica","g":3},{"rem":"glonoine","g":3},{"rem":"gelsemium","g":2},{"rem":"sanguinaria","g":3},{"rem":"natrum_mur","g":2},{"rem":"ignatia","g":2}]},
    "head_pain_morning":{"ur":"سر درد، صبح","en":"Headache, morning","roman":"Sar dard, subah","remedies":[{"rem":"nux_vomica","g":3},{"rem":"bryonia","g":2},{"rem":"natrum_mur","g":3},{"rem":"sulphur","g":2}]},
    "head_pain_evening":{"ur":"سر درد، شام","en":"Headache, evening","roman":"Sar dard, shaam","remedies":[{"rem":"pulsatilla","g":3},{"rem":"belladonna","g":2},{"rem":"lycopodium","g":2},{"rem":"causticum","g":2}]},
    "head_pain_right":{"ur":"سر درد، دائیں","en":"Headache, right side","roman":"Sar dard, dayen","remedies":[{"rem":"sanguinaria","g":3},{"rem":"belladonna","g":3},{"rem":"lycopodium","g":3},{"rem":"chelidonium","g":2},{"rem":"kali_bich","g":2}]},
    "head_pain_left":{"ur":"سر درد، بائیں","en":"Headache, left side","roman":"Sar dard, bayen","remedies":[{"rem":"spigelia","g":3},{"rem":"lachesis","g":2},{"rem":"sepia","g":2},{"rem":"phosphorus","g":2},{"rem":"iris","g":2}]},
    "head_pain_throbbing":{"ur":"سر درد، دھڑکنے والا","en":"Headache, throbbing","roman":"Sar dard, dharakne","remedies":[{"rem":"belladonna","g":3},{"rem":"glonoine","g":3},{"rem":"aconite","g":2},{"rem":"ferrum_met","g":2},{"rem":"bryonia","g":2}]},
    "head_pain_bursting":{"ur":"سر درد، پھٹنے والا","en":"Headache, bursting","roman":"Sar dard, phatne","remedies":[{"rem":"belladonna","g":3},{"rem":"glonoine","g":3},{"rem":"bryonia","g":2},{"rem":"china","g":2},{"rem":"natrum_mur","g":2}]},
    "head_pain_motion_agg":{"ur":"سر درد، حرکت سے","en":"Headache, motion agg","roman":"Sar dard, harkat","remedies":[{"rem":"bryonia","g":3},{"rem":"belladonna","g":2},{"rem":"nux_vomica","g":2}]},
    "head_pain_occiput":{"ur":"سر درد، گدی","en":"Headache, occiput","roman":"Sar dard, gaddi","remedies":[{"rem":"gelsemium","g":3},{"rem":"silicea","g":2},{"rem":"carbo_veg","g":2},{"rem":"petroleum","g":2}]},
    "head_pain_vertex":{"ur":"سر درد، چاندی","en":"Headache, vertex","roman":"Sar dard, chandi","remedies":[{"rem":"sepia","g":3},{"rem":"lachesis","g":2},{"rem":"sulphur","g":2},{"rem":"alumina","g":2}]},
    "head_pain_frontal":{"ur":"سر درد، پیشانی","en":"Headache, frontal","roman":"Sar dard, peshani","remedies":[{"rem":"nux_vomica","g":3},{"rem":"ignatia","g":2},{"rem":"pulsatilla","g":2},{"rem":"kali_bich","g":2},{"rem":"iris","g":2}]},
    "head_pain_sun":{"ur":"سر درد، دھوپ سے","en":"Headache, from sun","roman":"Sar dard, dhoop","remedies":[{"rem":"glonoine","g":3},{"rem":"belladonna","g":3},{"rem":"natrum_carb","g":3},{"rem":"lachesis","g":2},{"rem":"gelsemium","g":2}]},
    "head_pain_eye_strain":{"ur":"سر درد، آنکھوں کے زور","en":"Headache, eye strain","roman":"Sar dard, aankhon","remedies":[{"rem":"ruta","g":3},{"rem":"natrum_mur","g":3},{"rem":"phosphorus","g":2},{"rem":"gelsemium","g":2}]},
    "head_vertigo":{"ur":"چکر","en":"Vertigo","roman":"Chakkar","remedies":[{"rem":"belladonna","g":3},{"rem":"conium","g":3},{"rem":"cocculus","g":3},{"rem":"gelsemium","g":2},{"rem":"phosphorus","g":2},{"rem":"bryonia","g":2}]},
    "head_vertigo_motion":{"ur":"چکر، حرکت سے","en":"Vertigo, motion","roman":"Chakkar, harkat","remedies":[{"rem":"bryonia","g":3},{"rem":"cocculus","g":3},{"rem":"conium","g":2},{"rem":"belladonna","g":2}]},
    "head_vertigo_turning_bed":{"ur":"چکر، کروٹ بدلنے","en":"Vertigo, turning in bed","roman":"Chakkar, karwat","remedies":[{"rem":"conium","g":3},{"rem":"belladonna","g":2},{"rem":"phosphorus","g":2}]},
    "head_congestion":{"ur":"سر میں گرمی","en":"Congestion, head","roman":"Sar mein garmi","remedies":[{"rem":"belladonna","g":3},{"rem":"glonoine","g":3},{"rem":"aconite","g":2},{"rem":"ferrum_met","g":2},{"rem":"sulphur","g":2}]}
  }},
  "stomach": {"ur":"معدہ","en":"Stomach","roman":"Maida","rubrics":{
    "stomach_nausea":{"ur":"متلی","en":"Nausea","roman":"Matli","remedies":[{"rem":"ipecac","g":3},{"rem":"antimon_crud","g":2},{"rem":"pulsatilla","g":2},{"rem":"nux_vomica","g":2},{"rem":"sepia","g":2},{"rem":"arsenicum","g":2},{"rem":"colchicum","g":2}]},
    "stomach_nausea_fatty":{"ur":"متلی، چکنائی سے","en":"Nausea, fatty food","roman":"Matli, chiknai","remedies":[{"rem":"pulsatilla","g":3},{"rem":"carbo_veg","g":2},{"rem":"sepia","g":2},{"rem":"nux_vomica","g":2}]},
    "stomach_nausea_smell":{"ur":"متلی، کھانے کی بو سے","en":"Nausea, smell of food","roman":"Matli, bu","remedies":[{"rem":"colchicum","g":3},{"rem":"arsenicum","g":2},{"rem":"sepia","g":3},{"rem":"ipecac","g":2}]},
    "stomach_vomiting":{"ur":"قے","en":"Vomiting","roman":"Qay","remedies":[{"rem":"ipecac","g":3},{"rem":"arsenicum","g":3},{"rem":"nux_vomica","g":2},{"rem":"phosphorus","g":3},{"rem":"veratrum_alb","g":2},{"rem":"antimon_crud","g":2}]},
    "stomach_vomiting_bile":{"ur":"قے، صفرا","en":"Vomiting, bile","roman":"Qay, safra","remedies":[{"rem":"nux_vomica","g":2},{"rem":"iris","g":3},{"rem":"bryonia","g":2},{"rem":"pulsatilla","g":2},{"rem":"eupatorium","g":2}]},
    "stomach_appetite_wanting":{"ur":"بھوک نہ لگنا","en":"Appetite, wanting","roman":"Bhook nahi","remedies":[{"rem":"china","g":3},{"rem":"arsenicum","g":2},{"rem":"sepia","g":2},{"rem":"nux_vomica","g":2},{"rem":"ferrum_met","g":2}]},
    "stomach_desires_sweets":{"ur":"میٹھے کی خواہش","en":"Desires, sweets","roman":"Meetha","remedies":[{"rem":"argentum_nit","g":3},{"rem":"lycopodium","g":2},{"rem":"sulphur","g":2},{"rem":"china","g":2}]},
    "stomach_desires_salt":{"ur":"نمکین کی خواہش","en":"Desires, salt","roman":"Namkeen","remedies":[{"rem":"natrum_mur","g":3},{"rem":"carbo_veg","g":2},{"rem":"phosphorus","g":2},{"rem":"nitric_acid","g":3}]},
    "stomach_desires_sour":{"ur":"کھٹائی کی خواہش","en":"Desires, sour","roman":"Khattai","remedies":[{"rem":"veratrum_alb","g":2},{"rem":"hepar_sulph","g":3},{"rem":"phosphorus","g":2},{"rem":"sepia","g":2}]},
    "stomach_aversion_meat":{"ur":"گوشت سے نفرت","en":"Aversion, meat","roman":"Gosht","remedies":[{"rem":"calc_carb","g":3},{"rem":"pulsatilla","g":2},{"rem":"sepia","g":2},{"rem":"graphites","g":2},{"rem":"nitric_acid","g":2}]},
    "stomach_thirst":{"ur":"پیاس","en":"Thirst","roman":"Pyas","remedies":[{"rem":"arsenicum","g":3},{"rem":"bryonia","g":3},{"rem":"aconite","g":2},{"rem":"phosphorus","g":2},{"rem":"rhus_tox","g":2}]},
    "stomach_thirst_small":{"ur":"پیاس، تھوڑا تھوڑا","en":"Thirst, small qty","roman":"Pyas, thora","remedies":[{"rem":"arsenicum","g":3},{"rem":"china","g":2},{"rem":"ignatia","g":2},{"rem":"lycopodium","g":2}]},
    "stomach_thirst_large":{"ur":"پیاس، زیادہ","en":"Thirst, large qty","roman":"Pyas, zyada","remedies":[{"rem":"bryonia","g":3},{"rem":"phosphorus","g":3},{"rem":"aconite","g":2},{"rem":"natrum_mur","g":2}]},
    "stomach_thirstless":{"ur":"پیاس نہ لگنا","en":"Thirstless","roman":"Pyas nahi","remedies":[{"rem":"pulsatilla","g":3},{"rem":"apis","g":3},{"rem":"nux_moschata","g":3},{"rem":"gelsemium","g":2},{"rem":"antimon_crud","g":2}]},
    "stomach_heartburn":{"ur":"سینے کی جلن","en":"Heartburn","roman":"Seenay ki jalan","remedies":[{"rem":"nux_vomica","g":3},{"rem":"phosphorus","g":2},{"rem":"iris","g":3},{"rem":"carbo_veg","g":2},{"rem":"arsenicum","g":2}]},
    "stomach_eructations":{"ur":"ڈکار","en":"Eructations","roman":"Dakar","remedies":[{"rem":"nux_vomica","g":3},{"rem":"carbo_veg","g":3},{"rem":"china","g":3},{"rem":"lycopodium","g":2},{"rem":"pulsatilla","g":2},{"rem":"sulphur","g":2}]}
  }},
  "abdomen": {"ur":"پیٹ","en":"Abdomen","roman":"Pait","rubrics":{
    "abdomen_pain":{"ur":"پیٹ درد","en":"Pain, abdomen","roman":"Pait dard","remedies":[{"rem":"colocynth","g":3},{"rem":"nux_vomica","g":3},{"rem":"lycopodium","g":2},{"rem":"bryonia","g":2},{"rem":"china","g":2},{"rem":"dioscorea","g":3}]},
    "abdomen_pain_cramping":{"ur":"پیٹ درد، مروڑ","en":"Pain, cramping","roman":"Pait dard, maror","remedies":[{"rem":"colocynth","g":3},{"rem":"magnesia_phos","g":3},{"rem":"nux_vomica","g":2},{"rem":"dioscorea","g":2},{"rem":"cuprum_met","g":2}]},
    "abdomen_pain_bending_amel":{"ur":"پیٹ درد، دباؤ سے آرام","en":"Pain, bending amel","roman":"Pait dard, dabao","remedies":[{"rem":"colocynth","g":3},{"rem":"magnesia_phos","g":2},{"rem":"nux_vomica","g":2}]},
    "abdomen_pain_anger":{"ur":"پیٹ درد، غصے سے","en":"Pain, from anger","roman":"Pait dard, ghusse","remedies":[{"rem":"colocynth","g":3},{"rem":"staphysagria","g":3},{"rem":"chamomilla","g":3},{"rem":"nux_vomica","g":2}]},
    "abdomen_flatulence":{"ur":"ریاح","en":"Flatulence","roman":"Riyah","remedies":[{"rem":"lycopodium","g":3},{"rem":"carbo_veg","g":3},{"rem":"china","g":3},{"rem":"nux_vomica","g":2},{"rem":"argentum_nit","g":2}]},
    "abdomen_flatulence_obstructed":{"ur":"ریاح، پھنسی ہوئی","en":"Flatulence, obstructed","roman":"Riyah, phansi","remedies":[{"rem":"carbo_veg","g":3},{"rem":"china","g":3},{"rem":"lycopodium","g":2},{"rem":"raphanus","g":3}]},
    "abdomen_distension":{"ur":"پیٹ پھولنا","en":"Distension","roman":"Pait phoolna","remedies":[{"rem":"china","g":3},{"rem":"lycopodium","g":3},{"rem":"carbo_veg","g":3},{"rem":"pulsatilla","g":2},{"rem":"sepia","g":2}]},
    "abdomen_distension_after_eating":{"ur":"پیٹ پھولنا، کھانے بعد","en":"Distension, after eating","roman":"Pait phoolna, khana","remedies":[{"rem":"lycopodium","g":3},{"rem":"china","g":3},{"rem":"carbo_veg","g":2},{"rem":"nux_vomica","g":2},{"rem":"pulsatilla","g":2}]},
    "abdomen_liver_pain":{"ur":"جگر کا درد","en":"Liver, pain","roman":"Jigar dard","remedies":[{"rem":"chelidonium","g":3},{"rem":"bryonia","g":2},{"rem":"lycopodium","g":2},{"rem":"nux_vomica","g":2},{"rem":"mercurius","g":2}]},
    "abdomen_rumbling":{"ur":"پیٹ میں گڑگڑاہٹ","en":"Rumbling","roman":"Gargarahat","remedies":[{"rem":"lycopodium","g":3},{"rem":"aloe","g":2},{"rem":"pulsatilla","g":2},{"rem":"sulphur","g":2}]}
  }},
  "rectum": {"ur":"پاخانہ","en":"Rectum & Stool","roman":"Pakhanah","rubrics":{
    "rectum_constipation":{"ur":"قبض","en":"Constipation","roman":"Qabz","remedies":[{"rem":"nux_vomica","g":3},{"rem":"bryonia","g":3},{"rem":"lycopodium","g":2},{"rem":"silicea","g":2},{"rem":"alumina","g":3},{"rem":"graphites","g":2},{"rem":"sulphur","g":2},{"rem":"sepia","g":2}]},
    "rectum_constipation_no_desire":{"ur":"قبض، رغبت نہیں","en":"Constipation, no desire","roman":"Qabz, raghbat nahi","remedies":[{"rem":"alumina","g":3},{"rem":"bryonia","g":3},{"rem":"opium","g":3},{"rem":"nux_vomica","g":2},{"rem":"silicea","g":2}]},
    "rectum_diarrhea":{"ur":"دست","en":"Diarrhea","roman":"Dast","remedies":[{"rem":"arsenicum","g":3},{"rem":"china","g":3},{"rem":"podophyllum","g":3},{"rem":"phosphorus","g":2},{"rem":"veratrum_alb","g":3},{"rem":"sulphur","g":2},{"rem":"aloe","g":2}]},
    "rectum_diarrhea_morning":{"ur":"دست، صبح","en":"Diarrhea, morning","roman":"Dast, subah","remedies":[{"rem":"sulphur","g":3},{"rem":"podophyllum","g":3},{"rem":"aloe","g":3},{"rem":"bryonia","g":2},{"rem":"phosphorus","g":2}]},
    "rectum_diarrhea_after_eating":{"ur":"دست، کھانے بعد","en":"Diarrhea, after eating","roman":"Dast, khana","remedies":[{"rem":"china","g":3},{"rem":"ferrum_met","g":2},{"rem":"aloe","g":2},{"rem":"arsenicum","g":2}]},
    "rectum_hemorrhoids":{"ur":"بواسیر","en":"Hemorrhoids","roman":"Bawaseer","remedies":[{"rem":"nux_vomica","g":3},{"rem":"sulphur","g":3},{"rem":"hamamelis","g":3},{"rem":"aesculus","g":3},{"rem":"aloe","g":2},{"rem":"graphites","g":2}]}
  }},
  "cough": {"ur":"کھانسی","en":"Cough","roman":"Khansi","rubrics":{
    "cough_dry":{"ur":"کھانسی، خشک","en":"Cough, dry","roman":"Khansi, khushk","remedies":[{"rem":"bryonia","g":3},{"rem":"aconite","g":3},{"rem":"belladonna","g":3},{"rem":"phosphorus","g":3},{"rem":"hyoscyamus","g":2},{"rem":"ignatia","g":2},{"rem":"rumex","g":2}]},
    "cough_wet":{"ur":"کھانسی، بلغم","en":"Cough, loose","roman":"Khansi, balgham","remedies":[{"rem":"antimon_tart","g":3},{"rem":"ipecac","g":3},{"rem":"hepar_sulph","g":2},{"rem":"pulsatilla","g":2},{"rem":"kali_bich","g":2},{"rem":"stannum","g":2}]},
    "cough_night":{"ur":"کھانسی، رات","en":"Cough, night","roman":"Khansi, raat","remedies":[{"rem":"rumex","g":3},{"rem":"hyoscyamus","g":3},{"rem":"drosera","g":2},{"rem":"pulsatilla","g":2},{"rem":"chamomilla","g":2},{"rem":"arsenicum","g":2}]},
    "cough_morning":{"ur":"کھانسی، صبح","en":"Cough, morning","roman":"Khansi, subah","remedies":[{"rem":"bryonia","g":2},{"rem":"nux_vomica","g":2},{"rem":"sulphur","g":2},{"rem":"calc_carb","g":2}]},
    "cough_cold_air":{"ur":"کھانسی، ٹھنڈی ہوا","en":"Cough, cold air","roman":"Khansi, thandi hawa","remedies":[{"rem":"rumex","g":3},{"rem":"hepar_sulph","g":3},{"rem":"aconite","g":2},{"rem":"spongia","g":2},{"rem":"phosphorus","g":2}]},
    "cough_lying_agg":{"ur":"کھانسی، لیٹنے سے","en":"Cough, lying agg","roman":"Khansi, leitnay","remedies":[{"rem":"hyoscyamus","g":3},{"rem":"drosera","g":3},{"rem":"bryonia","g":2},{"rem":"arsenicum","g":2},{"rem":"conium","g":2}]},
    "cough_talking":{"ur":"کھانسی، بولنے سے","en":"Cough, talking","roman":"Khansi, bolnay","remedies":[{"rem":"rumex","g":3},{"rem":"drosera","g":2},{"rem":"phosphorus","g":2},{"rem":"hepar_sulph","g":2}]},
    "cough_spasmodic":{"ur":"کھانسی، تشنجی","en":"Cough, spasmodic","roman":"Khansi, tashannuji","remedies":[{"rem":"drosera","g":3},{"rem":"cuprum_met","g":3},{"rem":"ipecac","g":2},{"rem":"coccus_cacti","g":2},{"rem":"coralium","g":2}]},
    "cough_warm_room_agg":{"ur":"کھانسی، گرم کمرے میں","en":"Cough, warm room","roman":"Khansi, garam kamra","remedies":[{"rem":"pulsatilla","g":3},{"rem":"ipecac","g":2},{"rem":"apis","g":2}]},
    "cough_sitting_amel":{"ur":"کھانسی، بیٹھنے سے آرام","en":"Cough, sitting amel","roman":"Khansi, baithnay","remedies":[{"rem":"bryonia","g":2},{"rem":"hyoscyamus","g":3},{"rem":"arsenicum","g":2}]}
  }},
  "fever": {"ur":"بخار","en":"Fever","roman":"Bukhar","rubrics":{
    "fever_chill":{"ur":"سردی لگنا","en":"Chill","roman":"Thand","remedies":[{"rem":"aconite","g":3},{"rem":"arsenicum","g":2},{"rem":"china","g":2},{"rem":"nux_vomica","g":2},{"rem":"gelsemium","g":2}]},
    "fever_heat":{"ur":"بخار کی گرمی","en":"Heat, fever","roman":"Bukhar ki garmi","remedies":[{"rem":"aconite","g":3},{"rem":"belladonna","g":3},{"rem":"arsenicum","g":2},{"rem":"bryonia","g":2},{"rem":"phosphorus","g":2}]},
    "fever_heat_dry":{"ur":"بخار، خشک گرمی","en":"Heat, dry","roman":"Khushk garmi","remedies":[{"rem":"aconite","g":3},{"rem":"belladonna","g":2},{"rem":"bryonia","g":3},{"rem":"nux_vomica","g":2},{"rem":"arsenicum","g":2}]},
    "fever_heat_burning":{"ur":"بخار، جلن والی","en":"Heat, burning","roman":"Jalan wali garmi","remedies":[{"rem":"arsenicum","g":3},{"rem":"phosphorus","g":2},{"rem":"sulphur","g":2},{"rem":"aconite","g":2}]},
    "fever_perspiration":{"ur":"پسینہ","en":"Perspiration","roman":"Paseena","remedies":[{"rem":"china","g":3},{"rem":"mercurius","g":3},{"rem":"sulphur","g":2},{"rem":"belladonna","g":2},{"rem":"silicea","g":2},{"rem":"calc_carb","g":2}]},
    "fever_perspiration_night":{"ur":"پسینہ، رات","en":"Perspiration, night","roman":"Paseena, raat","remedies":[{"rem":"china","g":3},{"rem":"silicea","g":2},{"rem":"calc_carb","g":2},{"rem":"lycopodium","g":2},{"rem":"sulphur","g":2}]},
    "fever_perspiration_exhausting":{"ur":"پسینہ، تھکا دینے والا","en":"Perspiration, exhausting","roman":"Paseena, thaka","remedies":[{"rem":"china","g":3},{"rem":"veratrum_alb","g":3},{"rem":"arsenicum","g":2},{"rem":"carbo_veg","g":2}]},
    "fever_alternating":{"ur":"بخار، باری باری","en":"Alternating chill heat","roman":"Bukhar, bari bari","remedies":[{"rem":"china","g":3},{"rem":"aconite","g":2},{"rem":"arsenicum","g":2},{"rem":"ipecac","g":2}]}
  }},
  "extremities": {"ur":"ہاتھ پاؤں","en":"Extremities","roman":"Haath Paon","rubrics":{
    "extrem_pain_joints":{"ur":"جوڑوں کا درد","en":"Pain, joints","roman":"Joron dard","remedies":[{"rem":"rhus_tox","g":3},{"rem":"bryonia","g":3},{"rem":"pulsatilla","g":2},{"rem":"actea_spic","g":2},{"rem":"causticum","g":2},{"rem":"ledum","g":3}]},
    "extrem_pain_motion_amel":{"ur":"جوڑوں کا درد، حرکت سے آرام","en":"Pain, motion amel","roman":"Joron dard, harkat","remedies":[{"rem":"rhus_tox","g":3},{"rem":"pulsatilla","g":2},{"rem":"causticum","g":2}]},
    "extrem_pain_rest_amel":{"ur":"جوڑوں کا درد، آرام سے","en":"Pain, rest amel","roman":"Joron dard, aaram","remedies":[{"rem":"bryonia","g":3},{"rem":"ledum","g":2},{"rem":"calc_carb","g":2}]},
    "extrem_pain_cold_agg":{"ur":"جوڑوں کا درد، سردی سے","en":"Pain, cold agg","roman":"Joron dard, sardi","remedies":[{"rem":"rhus_tox","g":3},{"rem":"calc_carb","g":2},{"rem":"dulcamara","g":3},{"rem":"causticum","g":2}]},
    "extrem_pain_warm_amel":{"ur":"جوڑوں کا درد، گرمی سے","en":"Pain, warmth amel","roman":"Joron dard, garmi","remedies":[{"rem":"rhus_tox","g":3},{"rem":"arsenicum","g":2},{"rem":"causticum","g":2}]},
    "extrem_pain_wet_agg":{"ur":"جوڑوں کا درد، گیلے موسم","en":"Pain, wet agg","roman":"Joron dard, geela","remedies":[{"rem":"rhus_tox","g":3},{"rem":"dulcamara","g":3},{"rem":"calc_carb","g":2},{"rem":"natrum_sulph","g":2}]},
    "extrem_numbness":{"ur":"سن ہونا","en":"Numbness","roman":"Sun hona","remedies":[{"rem":"aconite","g":2},{"rem":"platinum","g":2},{"rem":"secale","g":2},{"rem":"causticum","g":2}]},
    "extrem_swelling":{"ur":"سوجن","en":"Swelling","roman":"Soojan","remedies":[{"rem":"apis","g":3},{"rem":"arsenicum","g":2},{"rem":"rhus_tox","g":2},{"rem":"bryonia","g":2},{"rem":"calc_carb","g":2}]},
    "extrem_cold_hands_feet":{"ur":"ہاتھ پاؤں ٹھنڈے","en":"Coldness, hands feet","roman":"Haath paon thande","remedies":[{"rem":"calc_carb","g":3},{"rem":"silicea","g":3},{"rem":"sepia","g":3},{"rem":"carbo_veg","g":2},{"rem":"nux_vomica","g":2}]},
    "extrem_cold_feet_burning":{"ur":"پاؤں ٹھنڈے جلتے","en":"Cold feet, burning","roman":"Paon thande jalte","remedies":[{"rem":"sulphur","g":3},{"rem":"secale","g":2},{"rem":"lachesis","g":2},{"rem":"calc_carb","g":2}]}
  }},
  "sleep": {"ur":"نیند","en":"Sleep","roman":"Neend","rubrics":{
    "sleep_sleeplessness":{"ur":"نیند نہ آنا","en":"Sleeplessness","roman":"Neend nahi","remedies":[{"rem":"coffea","g":3},{"rem":"nux_vomica","g":3},{"rem":"ignatia","g":2},{"rem":"arsenicum","g":2},{"rem":"pulsatilla","g":2},{"rem":"passiflora","g":2}]},
    "sleep_sleeplessness_thoughts":{"ur":"نیند نہیں، خیالات","en":"Sleeplessness, thoughts","roman":"Neend nahi, khayalat","remedies":[{"rem":"coffea","g":3},{"rem":"nux_vomica","g":3},{"rem":"ignatia","g":2},{"rem":"sulphur","g":2}]},
    "sleep_waking_early":{"ur":"صبح جلدی جاگنا","en":"Waking, early","roman":"Subah jaldi","remedies":[{"rem":"nux_vomica","g":3},{"rem":"sulphur","g":2},{"rem":"pulsatilla","g":2}]},
    "sleep_dreams_frightful":{"ur":"ڈراؤنے خواب","en":"Dreams, frightful","roman":"Daraone khwab","remedies":[{"rem":"aconite","g":2},{"rem":"belladonna","g":2},{"rem":"pulsatilla","g":2},{"rem":"stramonium","g":2},{"rem":"sulphur","g":2}]},
    "sleep_sleepy_day":{"ur":"دن میں نیند","en":"Sleepiness, daytime","roman":"Din mein neend","remedies":[{"rem":"nux_moschata","g":3},{"rem":"gelsemium","g":2},{"rem":"pulsatilla","g":2},{"rem":"opium","g":2}]},
    "sleep_restless":{"ur":"بے چین نیند","en":"Restless sleep","roman":"Be-chain neend","remedies":[{"rem":"arsenicum","g":3},{"rem":"aconite","g":2},{"rem":"belladonna","g":2},{"rem":"rhus_tox","g":2},{"rem":"chamomilla","g":2}]},
    "sleep_sleeplessness_midnight":{"ur":"نیند، آدھی رات بعد","en":"Sleeplessness, after midnight","roman":"Neend, aadhi raat","remedies":[{"rem":"arsenicum","g":3},{"rem":"nux_vomica","g":2},{"rem":"sulphur","g":2},{"rem":"kali_carb","g":2}]}
  }},
  "generalities": {"ur":"عمومیات","en":"Generalities","roman":"Umomiyat","rubrics":{
    "gen_weakness":{"ur":"کمزوری","en":"Weakness","roman":"Kamzori","remedies":[{"rem":"china","g":3},{"rem":"arsenicum","g":3},{"rem":"gelsemium","g":3},{"rem":"phosphorus","g":2},{"rem":"veratrum_alb","g":2},{"rem":"picric_acid","g":3}]},
    "gen_weakness_sudden":{"ur":"کمزوری، اچانک","en":"Weakness, sudden","roman":"Kamzori, achanak","remedies":[{"rem":"china","g":3},{"rem":"veratrum_alb","g":3},{"rem":"arsenicum","g":2},{"rem":"carbo_veg","g":2}]},
    "gen_cold_sensitive":{"ur":"سردی کی حساسیت","en":"Sensitive to cold","roman":"Sardi hasas","remedies":[{"rem":"silicea","g":3},{"rem":"calc_carb","g":3},{"rem":"hepar_sulph","g":3},{"rem":"psorinum","g":3},{"rem":"nux_vomica","g":2}]},
    "gen_heat_sensitive":{"ur":"گرمی کی حساسیت","en":"Sensitive to heat","roman":"Garmi hasas","remedies":[{"rem":"pulsatilla","g":3},{"rem":"iodum","g":3},{"rem":"apis","g":3},{"rem":"sulphur","g":3},{"rem":"lachesis","g":2}]},
    "gen_motion_agg":{"ur":"حرکت سے بڑھنا","en":"Motion agg","roman":"Harkat se barhna","remedies":[{"rem":"bryonia","g":3},{"rem":"belladonna","g":2},{"rem":"arsenicum","g":2},{"rem":"nux_vomica","g":2}]},
    "gen_motion_amel":{"ur":"حرکت سے آرام","en":"Motion amel","roman":"Harkat se aaram","remedies":[{"rem":"rhus_tox","g":3},{"rem":"pulsatilla","g":2},{"rem":"ferrum_met","g":2}]},
    "gen_open_air_desires":{"ur":"کھلی ہوا چاہیے","en":"Open air, desires","roman":"Khuli hawa","remedies":[{"rem":"pulsatilla","g":3},{"rem":"aconite","g":2},{"rem":"apis","g":2},{"rem":"ignatia","g":2}]},
    "gen_open_air_agg":{"ur":"کھلی ہوا سے بڑھنا","en":"Open air agg","roman":"Khuli hawa se","remedies":[{"rem":"nux_vomica","g":2},{"rem":"silicea","g":2},{"rem":"cocculus","g":2},{"rem":"kali_carb","g":2}]},
    "gen_wet_weather_agg":{"ur":"گیلے موسم سے","en":"Wet weather agg","roman":"Geela mausam","remedies":[{"rem":"dulcamara","g":3},{"rem":"rhus_tox","g":3},{"rem":"natrum_sulph","g":3},{"rem":"calc_carb","g":2}]},
    "gen_side_right":{"ur":"دائیں طرف","en":"Right side","roman":"Dayen taraf","remedies":[{"rem":"lycopodium","g":3},{"rem":"belladonna","g":2},{"rem":"bryonia","g":2},{"rem":"chelidonium","g":2},{"rem":"sanguinaria","g":2}]},
    "gen_side_left":{"ur":"بائیں طرف","en":"Left side","roman":"Bayen taraf","remedies":[{"rem":"lachesis","g":3},{"rem":"sulphur","g":2},{"rem":"spigelia","g":2},{"rem":"phosphorus","g":2}]},
    "gen_sleep_after_agg":{"ur":"نیند کے بعد بڑھنا","en":"After sleep agg","roman":"Neend ke baad","remedies":[{"rem":"lachesis","g":3},{"rem":"nux_vomica","g":2},{"rem":"sulphur","g":2},{"rem":"graphites","g":2}]},
    "gen_eating_after_agg":{"ur":"کھانے کے بعد بڑھنا","en":"After eating agg","roman":"Khanay ke baad","remedies":[{"rem":"nux_vomica","g":3},{"rem":"lycopodium","g":2},{"rem":"china","g":2},{"rem":"pulsatilla","g":2}]},
    "gen_fasting_agg":{"ur":"بھوک سے بڑھنا","en":"Fasting agg","roman":"Bhook se","remedies":[{"rem":"sulphur","g":3},{"rem":"lycopodium","g":2},{"rem":"china","g":2},{"rem":"ignatia","g":2}]},
    "gen_ascending_agg":{"ur":"چڑھنے سے بڑھنا","en":"Ascending agg","roman":"Charhnay se","remedies":[{"rem":"calc_carb","g":3},{"rem":"arsenicum","g":2},{"rem":"iodum","g":2}]}
  }}
};

var REMEDIES_DB_KENT = {
  "aconite":{"ur":"ایکونائٹ","en":"Aconitum Napellus","abbr":"Acon.","pot":"30C/200C","keynotes":{"ur":"اچانک شروع، شدید، بے چینی، موت کا خوف","en":"Sudden intense onset, anxiety, fear of death"}},
  "arsenicum":{"ur":"آرسینکم البم","en":"Arsenicum Album","abbr":"Ars.","pot":"30C/200C-1M","keynotes":{"ur":"بے چینی، جلن، تھوڑا پانی، آدھی رات بڑھنا","en":"Anxiety, burning, sips water, worse midnight"}},
  "belladonna":{"ur":"بیلاڈونا","en":"Belladonna","abbr":"Bell.","pot":"30C/200C","keynotes":{"ur":"سرخ چہرہ، دھڑکنے والا درد، روشنی و شور سے بڑھنا","en":"Red face, throbbing pain, worse light noise"}},
  "nux_vomica":{"ur":"نکس وامیکا","en":"Nux Vomica","abbr":"Nux-v.","pot":"30C/200C-1M","keynotes":{"ur":"چڑچڑاپن، صبح بڑھنا، کافی و مصالحے سے","en":"Irritable, worse morning, coffee spices"}},
  "bryonia":{"ur":"برایونیا","en":"Bryonia Alba","abbr":"Bry.","pot":"30C/200C-1M","keynotes":{"ur":"خشک درد، حرکت سے بڑھے، آرام سے آرام، شدید پیاس","en":"Dry pains, worse motion, better rest, thirst"}},
  "pulsatilla":{"ur":"پلسیٹیلا","en":"Pulsatilla","abbr":"Puls.","pot":"30C/200C","keynotes":{"ur":"نرم مزاج، رونا، تسلی سے آرام، پیاس نہیں","en":"Mild weepy, consolation amel, thirstless"}},
  "rhus_tox":{"ur":"رس ٹاکس","en":"Rhus Toxicodendron","abbr":"Rhus-t.","pot":"30C/200C","keynotes":{"ur":"جوڑوں کا درد، حرکت سے آرام، گیلے موسم سے","en":"Joint pain, motion amel, worse cold wet"}},
  "lycopodium":{"ur":"لائیکوپوڈیم","en":"Lycopodium","abbr":"Lyc.","pot":"30C/200C-1M","keynotes":{"ur":"شام 4-8، ریاح، دائیں طرف، میٹھا","en":"Worse 4-8PM, flatulence, right-sided, sweets"}},
  "phosphorus":{"ur":"فاسفورس","en":"Phosphorus","abbr":"Phos.","pot":"30C/200C","keynotes":{"ur":"خون بہنا، جلن، ٹھنڈا پانی گرم قے","en":"Bleeding, burning, cold water vomited warm"}},
  "sulphur":{"ur":"سلفر","en":"Sulphur","abbr":"Sulph.","pot":"30C/200C-1M","keynotes":{"ur":"جلن، بدبو، نہانے سے بڑھنا، پاؤں جلن","en":"Burning, offensive, worse bathing, burning feet"}},
  "china":{"ur":"چائنا","en":"China Officinalis","abbr":"Chin.","pot":"30C/200C","keynotes":{"ur":"کمزوری، پیٹ پھولنا، بھوک مگر جلد پیٹ بھرنا","en":"Weakness, flatulence, hungry quick satiety"}},
  "ignatia":{"ur":"اگنیشیا","en":"Ignatia Amara","abbr":"Ign.","pot":"30C/200C","keynotes":{"ur":"غم و صدمہ، گلے میں گولا، آہ بھرنا","en":"Grief shock, lump throat, sighing"}},
  "natrum_mur":{"ur":"نیٹرم میور","en":"Natrum Muriaticum","abbr":"Nat-m.","pot":"30C/200C-1M","keynotes":{"ur":"اداسی، تنہائی، تسلی سے بڑھنا، نمکین","en":"Sad solitary, worse consolation, salt desire"}},
  "sepia":{"ur":"سیپیا","en":"Sepia Officinalis","abbr":"Sep.","pot":"30C/200C-1M","keynotes":{"ur":"بے حسی، تھکاوٹ، چاندی پر درد، حیض","en":"Indifferent tired, vertex pain, menses"}},
  "lachesis":{"ur":"لیکیسس","en":"Lachesis Muta","abbr":"Lach.","pot":"30C/200C-1M","keynotes":{"ur":"بائیں طرف، نیند بعد، تنگ کپڑے نہیں","en":"Left-sided, worse after sleep, tight clothes"}},
  "gelsemium":{"ur":"جیلسیمیم","en":"Gelsemium","abbr":"Gels.","pot":"30C/200C","keynotes":{"ur":"کمزوری، کپکپی، گدی درد، امتحان ڈر","en":"Weak trembling, occipital pain, exam fear"}},
  "chamomilla":{"ur":"کیموملا","en":"Chamomilla","abbr":"Cham.","pot":"30C/200C","keynotes":{"ur":"بہت چڑچڑا، کچھ برداشت نہیں، دانت","en":"Very irritable, cannot bear, teething"}},
  "mercurius":{"ur":"مرکیوریس","en":"Mercurius Sol","abbr":"Merc.","pot":"30C/200C","keynotes":{"ur":"بدبودار منہ، لعاب، رات کو، بے آرام پسینہ","en":"Offensive mouth, saliva, night, sweat"}},
  "ipecac":{"ur":"اپیکیاک","en":"Ipecacuanha","abbr":"Ip.","pot":"30C/200C","keynotes":{"ur":"مسلسل متلی، قے سے آرام نہیں","en":"Constant nausea, vomiting no relief"}},
  "apis":{"ur":"ایپس میلیفکا","en":"Apis Mellifica","abbr":"Apis.","pot":"30C/200C","keynotes":{"ur":"سوجن، چبھنے والا درد، گرمی، پیاس نہیں","en":"Swelling stinging, worse heat, thirstless"}},
  "calc_carb":{"ur":"کیلکیریا کارب","en":"Calcarea Carbonica","abbr":"Calc.","pot":"200C/1M","keynotes":{"ur":"موٹے سست، ٹھنڈ پسند، سر پسینہ، انڈے","en":"Fat sluggish chilly, head sweat, eggs"}},
  "silicea":{"ur":"سلیشیا","en":"Silicea","abbr":"Sil.","pot":"30C/200C-1M","keynotes":{"ur":"سردی حساس، کمزور، اعتماد کی کمی، پیپ","en":"Chilly weak, no confidence, pus"}},
  "hepar_sulph":{"ur":"ہیپر سلف","en":"Hepar Sulphuris","abbr":"Hep.","pot":"30C/200C","keynotes":{"ur":"سردی سے بہت حساس، پیپ، چھینکیں","en":"Extremely chilly, pus, sneezes"}},
  "colocynth":{"ur":"کولوسنتھس","en":"Colocynthis","abbr":"Coloc.","pot":"30C/200C","keynotes":{"ur":"مروڑ والا پیٹ درد، دباؤ سے آرام","en":"Cramping pain, better pressure"}},
  "carbo_veg":{"ur":"کاربو ویج","en":"Carbo Vegetabilis","abbr":"Carb-v.","pot":"30C/200C","keynotes":{"ur":"شدید کمزوری، ٹھنڈی جلد، پنکھا، ریاح","en":"Extreme weakness, cold, wants fan, gas"}},
  "veratrum_alb":{"ur":"ویرٹرم البم","en":"Veratrum Album","abbr":"Verat.","pot":"30C/200C","keynotes":{"ur":"شدید کمزوری، ٹھنڈا پسینہ، قے دست","en":"Extreme weakness, cold sweat"}},
  "dulcamara":{"ur":"ڈلکامارا","en":"Dulcamara","abbr":"Dulc.","pot":"30C/200C","keynotes":{"ur":"گیلے موسم بارش، سردی لگ کر بخار","en":"Worse wet rain, fever catching cold"}},
  "staphysagria":{"ur":"اسٹیفسیگریا","en":"Staphysagria","abbr":"Staph.","pot":"30C/200C-1M","keynotes":{"ur":"دبا غصہ، بے عزتی، صدمہ","en":"Suppressed anger, indignation, shock"}},
  "glonoine":{"ur":"گلونوئن","en":"Glonoinum","abbr":"Glon.","pot":"30C/200C","keynotes":{"ur":"دھوپ سے سر درد، دھڑکن، خون بہاؤ","en":"Sun headache, throbbing, blood rush"}},
  "argentum_nit":{"ur":"آرجینٹم نائٹ","en":"Argentum Nitricum","abbr":"Arg-n.","pot":"30C/200C","keynotes":{"ur":"جلد بازی، وقت آہستہ، امتحان ڈر","en":"Hasty, time slow, exam fear"}},
  "drosera":{"ur":"ڈروسیرا","en":"Drosera","abbr":"Dros.","pot":"30C/200C","keynotes":{"ur":"کالی کھانسی، لیٹنے بولنے سے، رات","en":"Whooping cough, worse lying talking"}},
  "rumex":{"ur":"رومیکس","en":"Rumex Crispus","abbr":"Rumx.","pot":"30C/200C","keynotes":{"ur":"ٹھنڈی ہوا سے کھانسی، بولنے سے","en":"Cough from cold air, talking"}},
  "antimon_tart":{"ur":"اینٹیمون ٹارٹ","en":"Antimonium Tart","abbr":"Ant-t.","pot":"30C/200C","keynotes":{"ur":"بلغم والی کھانسی، گھرگھراہٹ","en":"Rattling cough, wheezing"}},
  "spongia":{"ur":"اسپونجیا","en":"Spongia Tosta","abbr":"Spong.","pot":"30C/200C","keynotes":{"ur":"خشک بھونکنے والی کھانسی","en":"Dry barking cough"}},
  "hyoscyamus":{"ur":"ہایوسائمس","en":"Hyoscyamus","abbr":"Hyos.","pot":"30C/200C","keynotes":{"ur":"رات کھانسی، لیٹنے سے، بیٹھنے آرام","en":"Night cough, lying agg, sitting amel"}},
  "podophyllum":{"ur":"پوڈوفائلم","en":"Podophyllum","abbr":"Podo.","pot":"30C/200C","keynotes":{"ur":"صبح دست، بغیر درد، گڑگڑاہٹ","en":"Morning diarrhea, painless, gushing"}},
  "aloe":{"ur":"ایلو","en":"Aloe Socotrina","abbr":"Aloe.","pot":"30C/200C","keynotes":{"ur":"صبح دست، پیٹ گڑگڑاہٹ، بواسیر","en":"Morning diarrhea, rumbling, hemorrhoids"}},
  "coffea":{"ur":"کوفیا","en":"Coffea Cruda","abbr":"Coff.","pot":"30C/200C","keynotes":{"ur":"نیند نہیں، خیالات کی بھرمار","en":"Sleepless, rush of thoughts"}},
  "ledum":{"ur":"لیڈم","en":"Ledum Palustre","abbr":"Led.","pot":"30C/200C","keynotes":{"ur":"جوڑوں کا درد، ٹھنڈ سے آرام","en":"Joint pain, better cold"}},
  "sanguinaria":{"ur":"سنگوینیریا","en":"Sanguinaria","abbr":"Sang.","pot":"30C/200C","keynotes":{"ur":"دائیں سر درد، دھوپ، متلی","en":"Right headache, sun, nausea"}},
  "colchicum":{"ur":"کولچیکم","en":"Colchicum","abbr":"Colch.","pot":"30C/200C","keynotes":{"ur":"متلی، کھانے کی بو، جوڑوں کا درد","en":"Nausea from smell, joint pain"}},
  "chelidonium":{"ur":"کلیڈونیم","en":"Chelidonium Majus","abbr":"Chel.","pot":"30C/200C","keynotes":{"ur":"جگر درد، دائیں طرف","en":"Liver pain, right side"}}
};

console.log("✅ Repertory: 10 chapters, 117 rubrics, 42 remedies");