// ==========================================
// Bismillah Clinic — Repertory Data (Kent Style)
// Chapters: Mind, Head, Stomach, Abdomen,
//           Fever, Cough, Extremities, Generalities
// ==========================================

var REPERTORY_DATA = {
  "mind": {
    ur: "دماغ / ذہن", en: "Mind", roman: "Dimagh / Zehen",
    rubrics: {
      "mind_anger": { ur: "غصہ", en: "Anger, irascibility", roman: "Ghussa",
        remedies: [{rem:"nux_vomica",grade:3},{rem:"chamomilla",grade:3},{rem:"bryonia",grade:2},{rem:"staphysagria",grade:3},{rem:"aconite",grade:2},{rem:"ignatia",grade:2},{rem:"natrum_mur",grade:2},{rem:"lycopodium",grade:2}] },
      "mind_anger_silent": { ur: "غصہ، خاموش", en: "Anger, silent, suppressed", roman: "Ghussa, khamosh",
        remedies: [{rem:"staphysagria",grade:3},{rem:"ignatia",grade:3},{rem:"natrum_mur",grade:2},{rem:"aurum_met",grade:2},{rem:"colocynth",grade:2}] },
      "mind_anxiety": { ur: "بے چینی", en: "Anxiety", roman: "Bechaini",
        remedies: [{rem:"aconite",grade:3},{rem:"arsenicum",grade:3},{rem:"phosphorus",grade:2},{rem:"pulsatilla",grade:2},{rem:"gelsemium",grade:2},{rem:"argentum_nit",grade:2},{rem:"ignatia",grade:2}] },
      "mind_anxiety_health": { ur: "بے چینی، صحت کے بارے میں", en: "Anxiety, about health", roman: "Bechaini, sehat ke baray mein",
        remedies: [{rem:"arsenicum",grade:3},{rem:"phosphorus",grade:3},{rem:"calcarea_carb",grade:2},{rem:"nitric_acid",grade:2}] },
      "mind_sadness": { ur: "اداسی", en: "Sadness, depression", roman: "Udasi",
        remedies: [{rem:"ignatia",grade:3},{rem:"natrum_mur",grade:3},{rem:"pulsatilla",grade:2},{rem:"aurum_met",grade:3},{rem:"sepia",grade:2},{rem:"lachesis",grade:2}] },
      "mind_fear": { ur: "خوف", en: "Fear", roman: "Khauf",
        remedies: [{rem:"aconite",grade:3},{rem:"arsenicum",grade:2},{rem:"phosphorus",grade:2},{rem:"gelsemium",grade:2},{rem:"opium",grade:2},{rem:"stramonium",grade:2}] },
      "mind_fear_death": { ur: "خوف، موت کا", en: "Fear, of death", roman: "Khauf, maut ka",
        remedies: [{rem:"aconite",grade:3},{rem:"arsenicum",grade:3},{rem:"phosphorus",grade:2},{rem:"gelsemium",grade:2},{rem:"lachesis",grade:2}] },
      "mind_weeping": { ur: "رونا", en: "Weeping, tearful", roman: "Rona",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"ignatia",grade:3},{rem:"natrum_mur",grade:2},{rem:"sepia",grade:2}] },
      "mind_weeping_consolation_agg": { ur: "رونا، تسلی سے بڑھے", en: "Weeping, consolation aggravates", roman: "Rona, tasalli se barhe",
        remedies: [{rem:"natrum_mur",grade:3},{rem:"ignatia",grade:2},{rem:"sepia",grade:3}] },
      "mind_weeping_consolation_amel": { ur: "رونا، تسلی سے کم ہو", en: "Weeping, consolation ameliorates", roman: "Rona, tasalli se kam ho",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"phosphorus",grade:2},{rem:"calcarea_carb",grade:2}] }
    }
  },
  "head": {
    ur: "سر", en: "Head", roman: "Sar",
    rubrics: {
      "head_pain": { ur: "سر درد", en: "Headache", roman: "Sar dard",
        remedies: [{rem:"belladonna",grade:3},{rem:"bryonia",grade:3},{rem:"nux_vomica",grade:3},{rem:"glonoine",grade:3},{rem:"gelsemium",grade:2},{rem:"sanguinaria",grade:3},{rem:"natrum_mur",grade:2}] },
      "head_pain_morning": { ur: "سر درد، صبح", en: "Headache, morning", roman: "Sar dard, subah",
        remedies: [{rem:"nux_vomica",grade:3},{rem:"bryonia",grade:2},{rem:"natrum_mur",grade:3},{rem:"sulphur",grade:2}] },
      "head_pain_evening": { ur: "سر درد، شام", en: "Headache, evening", roman: "Sar dard, shaam",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"belladonna",grade:2},{rem:"lycopodium",grade:2}] },
      "head_pain_right": { ur: "سر درد، دائیں طرف", en: "Headache, right side", roman: "Sar dard, dayen",
        remedies: [{rem:"sanguinaria",grade:3},{rem:"belladonna",grade:3},{rem:"lycopodium",grade:3},{rem:"chelidonium",grade:2}] },
      "head_pain_left": { ur: "سر درد، بائیں طرف", en: "Headache, left side", roman: "Sar dard, bayen",
        remedies: [{rem:"spigelia",grade:3},{rem:"lachesis",grade:2},{rem:"sepia",grade:2},{rem:"phosphorus",grade:2}] },
      "head_pain_throbbing": { ur: "سر درد، دھڑکنے والا", en: "Headache, throbbing", roman: "Sar dard, dharakne wala",
        remedies: [{rem:"belladonna",grade:3},{rem:"glonoine",grade:3},{rem:"aconite",grade:2},{rem:"ferrum_met",grade:2}] },
      "head_pain_bursting": { ur: "سر درد، پھٹنے والا", en: "Headache, bursting", roman: "Sar dard, phatne wala",
        remedies: [{rem:"belladonna",grade:3},{rem:"glonoine",grade:3},{rem:"bryonia",grade:2},{rem:"china",grade:2}] },
      "head_pain_motion_agg": { ur: "سر درد، حرکت سے بڑھے", en: "Headache, motion aggravates", roman: "Sar dard, harkat se barhe",
        remedies: [{rem:"bryonia",grade:3},{rem:"belladonna",grade:2},{rem:"nux_vomica",grade:2}] },
      "head_pain_occiput": { ur: "سر درد، گدی میں", en: "Headache, occiput", roman: "Sar dard, gaddi mein",
        remedies: [{rem:"gelsemium",grade:3},{rem:"silicea",grade:2},{rem:"carbo_veg",grade:2}] },
      "head_pain_vertex": { ur: "سر درد، چاندی پر", en: "Headache, vertex", roman: "Sar dard, chandi par",
        remedies: [{rem:"sepia",grade:3},{rem:"lachesis",grade:2},{rem:"sulphur",grade:2},{rem:"alumina",grade:2}] },
      "head_pain_frontal": { ur: "سر درد، پیشانی", en: "Headache, frontal", roman: "Sar dard, peshani",
        remedies: [{rem:"nux_vomica",grade:3},{rem:"ignatia",grade:2},{rem:"pulsatilla",grade:2},{rem:"kali_bich",grade:2}] },
      "head_pain_sun": { ur: "سر درد، دھوپ سے", en: "Headache, from sun", roman: "Sar dard, dhoop se",
        remedies: [{rem:"glonoine",grade:3},{rem:"belladonna",grade:3},{rem:"natrum_carb",grade:3},{rem:"lachesis",grade:2},{rem:"gelsemium",grade:2}] },
      "head_vertigo": { ur: "چکر", en: "Vertigo", roman: "Chakkar",
        remedies: [{rem:"belladonna",grade:3},{rem:"conium",grade:3},{rem:"cocculus",grade:3},{rem:"gelsemium",grade:2},{rem:"phosphorus",grade:2},{rem:"bryonia",grade:2}] }
    }
  },
  "stomach": {
    ur: "معدہ", en: "Stomach", roman: "Maida",
    rubrics: {
      "stomach_nausea": { ur: "متلی", en: "Nausea", roman: "Matli",
        remedies: [{rem:"ipecac",grade:3},{rem:"pulsatilla",grade:2},{rem:"nux_vomica",grade:2},{rem:"sepia",grade:2},{rem:"arsenicum",grade:2},{rem:"colchicum",grade:2}] },
      "stomach_nausea_fatty": { ur: "متلی، چکنائی سے", en: "Nausea, from fatty food", roman: "Matli, chiknai se",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"carbo_veg",grade:2},{rem:"sepia",grade:2}] },
      "stomach_nausea_smell": { ur: "متلی، کھانے کی بو سے", en: "Nausea, from smell of food", roman: "Matli, khanay ki bu se",
        remedies: [{rem:"colchicum",grade:3},{rem:"arsenicum",grade:2},{rem:"sepia",grade:3}] },
      "stomach_vomiting": { ur: "قے", en: "Vomiting", roman: "Qay",
        remedies: [{rem:"ipecac",grade:3},{rem:"arsenicum",grade:3},{rem:"nux_vomica",grade:2},{rem:"phosphorus",grade:3},{rem:"veratrum_alb",grade:2}] },
      "stomach_vomiting_bile": { ur: "قے، صفرا", en: "Vomiting, bile", roman: "Qay, safra",
        remedies: [{rem:"nux_vomica",grade:2},{rem:"iris",grade:3},{rem:"bryonia",grade:2},{rem:"pulsatilla",grade:2},{rem:"eupatorium",grade:2}] },
      "stomach_appetite_wanting": { ur: "بھوک نہ لگنا", en: "Appetite, wanting", roman: "Bhook nah lagna",
        remedies: [{rem:"china",grade:3},{rem:"arsenicum",grade:2},{rem:"sepia",grade:2},{rem:"nux_vomica",grade:2}] },
      "stomach_desires_sweets": { ur: "میٹھے کی خواہش", en: "Desires, sweets", roman: "Meethe ki khwahish",
        remedies: [{rem:"argentum_nit",grade:3},{rem:"lycopodium",grade:2},{rem:"sulphur",grade:2},{rem:"china",grade:2}] },
      "stomach_desires_salt": { ur: "نمکین کی خواہش", en: "Desires, salt", roman: "Namkeen ki khwahish",
        remedies: [{rem:"natrum_mur",grade:3},{rem:"carbo_veg",grade:2},{rem:"phosphorus",grade:2},{rem:"nitric_acid",grade:3}] },
      "stomach_aversion_meat": { ur: "گوشت سے نفرت", en: "Aversion, meat", roman: "Gosht se nafrat",
        remedies: [{rem:"calc_carb",grade:3},{rem:"pulsatilla",grade:2},{rem:"sepia",grade:2},{rem:"graphites",grade:2},{rem:"nitric_acid",grade:2}] },
      "stomach_thirst": { ur: "پیاس", en: "Thirst", roman: "Pyas",
        remedies: [{rem:"arsenicum",grade:3},{rem:"bryonia",grade:3},{rem:"aconite",grade:2},{rem:"phosphorus",grade:2},{rem:"rhus_tox",grade:2}] },
      "stomach_thirst_small": { ur: "پیاس، تھوڑا تھوڑا", en: "Thirst, small quantities", roman: "Pyas, thora thora",
        remedies: [{rem:"arsenicum",grade:3},{rem:"china",grade:2},{rem:"ignatia",grade:2},{rem:"lycopodium",grade:2}] },
      "stomach_thirst_large": { ur: "پیاس، زیادہ مقدار", en: "Thirst, large quantities", roman: "Pyas, zyada miqdar",
        remedies: [{rem:"bryonia",grade:3},{rem:"phosphorus",grade:3},{rem:"aconite",grade:2},{rem:"natrum_mur",grade:2}] },
      "stomach_thirstless": { ur: "پیاس نہ لگنا", en: "Thirstless", roman: "Pyas nah lagna",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"apis",grade:3},{rem:"gelsemium",grade:2},{rem:"antimon_crud",grade:2}] }
    }
  },
  "abdomen": {
    ur: "پیٹ", en: "Abdomen", roman: "Pait",
    rubrics: {
      "abdomen_pain": { ur: "پیٹ درد", en: "Pain, abdomen", roman: "Pait dard",
        remedies: [{rem:"colocynth",grade:3},{rem:"nux_vomica",grade:3},{rem:"lycopodium",grade:2},{rem:"bryonia",grade:2},{rem:"china",grade:2},{rem:"dioscorea",grade:3}] },
      "abdomen_pain_cramping": { ur: "پیٹ درد، مروڑ", en: "Pain, cramping", roman: "Pait dard, maror",
        remedies: [{rem:"colocynth",grade:3},{rem:"magnesia_phos",grade:3},{rem:"nux_vomica",grade:2},{rem:"dioscorea",grade:2},{rem:"cuprum_met",grade:2}] },
      "abdomen_pain_bending_amel": { ur: "پیٹ درد، دباؤ سے آرام", en: "Pain, bending double ameliorates", roman: "Pait dard, dabao se aaram",
        remedies: [{rem:"colocynth",grade:3},{rem:"magnesia_phos",grade:2},{rem:"nux_vomica",grade:2}] },
      "abdomen_pain_anger": { ur: "پیٹ درد، غصے سے", en: "Pain, from anger", roman: "Pait dard, ghusse se",
        remedies: [{rem:"colocynth",grade:3},{rem:"staphysagria",grade:3},{rem:"chamomilla",grade:3},{rem:"nux_vomica",grade:2}] },
      "abdomen_flatulence": { ur: "ریاح", en: "Flatulence", roman: "Riyah",
        remedies: [{rem:"lycopodium",grade:3},{rem:"carbo_veg",grade:3},{rem:"china",grade:3},{rem:"nux_vomica",grade:2},{rem:"raphanus",grade:2},{rem:"argentum_nit",grade:2}] },
      "abdomen_flatulence_obstructed": { ur: "ریاح، پھنسی ہوئی", en: "Flatulence, incarcerated", roman: "Riyah, phansi hui",
        remedies: [{rem:"carbo_veg",grade:3},{rem:"china",grade:3},{rem:"lycopodium",grade:2},{rem:"raphanus",grade:3}] },
      "abdomen_distension_after_eating": { ur: "پیٹ پھولنا، کھانے کے بعد", en: "Distension, after eating", roman: "Pait phoolna, khanay ke baad",
        remedies: [{rem:"lycopodium",grade:3},{rem:"china",grade:3},{rem:"carbo_veg",grade:2},{rem:"nux_vomica",grade:2},{rem:"pulsatilla",grade:2}] }
    }
  },
  "fever": {
    ur: "بخار", en: "Fever", roman: "Bukhar",
    rubrics: {
      "fever_chill": { ur: "سردی لگنا", en: "Chill", roman: "Thand lagna",
        remedies: [{rem:"aconite",grade:3},{rem:"arsenicum",grade:2},{rem:"china",grade:2},{rem:"gelsemium",grade:2}] },
      "fever_heat": { ur: "بخار کی گرمی", en: "Heat, fever", roman: "Bukhar ki garmi",
        remedies: [{rem:"aconite",grade:3},{rem:"belladonna",grade:3},{rem:"arsenicum",grade:2},{rem:"bryonia",grade:2},{rem:"phosphorus",grade:2}] },
      "fever_heat_dry": { ur: "بخار، خشک گرمی", en: "Heat, dry", roman: "Bukhar, khushk garmi",
        remedies: [{rem:"aconite",grade:3},{rem:"belladonna",grade:2},{rem:"bryonia",grade:3},{rem:"nux_vomica",grade:2},{rem:"arsenicum",grade:2}] },
      "fever_perspiration": { ur: "پسینہ", en: "Perspiration", roman: "Paseena",
        remedies: [{rem:"china",grade:3},{rem:"mercurius",grade:3},{rem:"sulphur",grade:2},{rem:"belladonna",grade:2},{rem:"silicea",grade:2}] },
      "fever_perspiration_night": { ur: "پسینہ، رات کو", en: "Perspiration, night", roman: "Paseena, raat ko",
        remedies: [{rem:"china",grade:3},{rem:"silicea",grade:2},{rem:"calc_carb",grade:2},{rem:"lycopodium",grade:2}] }
    }
  },
  "cough": {
    ur: "کھانسی", en: "Cough", roman: "Khansi",
    rubrics: {
      "cough_dry": { ur: "کھانسی، خشک", en: "Cough, dry", roman: "Khansi, khushk",
        remedies: [{rem:"bryonia",grade:3},{rem:"aconite",grade:3},{rem:"belladonna",grade:3},{rem:"phosphorus",grade:3},{rem:"hyoscyamus",grade:2},{rem:"ignatia",grade:2}] },
      "cough_wet": { ur: "کھانسی، بلغم والی", en: "Cough, loose, rattling", roman: "Khansi, balgham wali",
        remedies: [{rem:"antimon_tart",grade:3},{rem:"ipecac",grade:3},{rem:"hepar_sulph",grade:2},{rem:"pulsatilla",grade:2},{rem:"kali_bich",grade:2}] },
      "cough_night": { ur: "کھانسی، رات کو", en: "Cough, night", roman: "Khansi, raat ko",
        remedies: [{rem:"rumex",grade:3},{rem:"hyoscyamus",grade:3},{rem:"drosera",grade:2},{rem:"pulsatilla",grade:2},{rem:"arsenicum",grade:2}] },
      "cough_morning": { ur: "کھانسی، صبح", en: "Cough, morning", roman: "Khansi, subah",
        remedies: [{rem:"bryonia",grade:2},{rem:"nux_vomica",grade:2},{rem:"sulphur",grade:2}] },
      "cough_cold_air": { ur: "کھانسی، ٹھنڈی ہوا سے", en: "Cough, from cold air", roman: "Khansi, thandi hawa se",
        remedies: [{rem:"rumex",grade:3},{rem:"aconite",grade:2},{rem:"hepar_sulph",grade:3},{rem:"spongia",grade:2},{rem:"phosphorus",grade:2}] },
      "cough_lying_agg": { ur: "کھانسی، لیٹنے سے بڑھے", en: "Cough, lying aggravates", roman: "Khansi, leitnay se barhe",
        remedies: [{rem:"hyoscyamus",grade:3},{rem:"drosera",grade:3},{rem:"bryonia",grade:2},{rem:"arsenicum",grade:2}] },
      "cough_talking": { ur: "کھانسی، بولنے سے", en: "Cough, from talking", roman: "Khansi, bolnay se",
        remedies: [{rem:"rumex",grade:3},{rem:"drosera",grade:2},{rem:"phosphorus",grade:2},{rem:"hepar_sulph",grade:2}] }
    }
  },
  "extremities": {
    ur: "ہاتھ پاؤں", en: "Extremities", roman: "Haath Paon",
    rubrics: {
      "extremities_pain_joints": { ur: "جوڑوں کا درد", en: "Pain, joints", roman: "Joron ka dard",
        remedies: [{rem:"rhus_tox",grade:3},{rem:"bryonia",grade:3},{rem:"pulsatilla",grade:2},{rem:"actea_spic",grade:2},{rem:"causticum",grade:2},{rem:"ledum",grade:3}] },
      "extremities_pain_motion_amel": { ur: "جوڑوں کا درد، حرکت سے آرام", en: "Pain, motion ameliorates", roman: "Joron ka dard, harkat se aaram",
        remedies: [{rem:"rhus_tox",grade:3},{rem:"pulsatilla",grade:2},{rem:"causticum",grade:2}] },
      "extremities_pain_rest_amel": { ur: "جوڑوں کا درد، آرام سے آرام", en: "Pain, rest ameliorates", roman: "Joron ka dard, aaram se aaram",
        remedies: [{rem:"bryonia",grade:3},{rem:"ledum",grade:2},{rem:"calc_carb",grade:2}] },
      "extremities_pain_cold_agg": { ur: "جوڑوں کا درد، ٹھنڈ سے بڑھے", en: "Pain, cold aggravates", roman: "Joron ka dard, thand se barhe",
        remedies: [{rem:"rhus_tox",grade:3},{rem:"calc_carb",grade:2},{rem:"dulcamara",grade:3},{rem:"causticum",grade:2}] },
      "extremities_pain_warm_amel": { ur: "جوڑوں کا درد، گرمی سے آرام", en: "Pain, warmth ameliorates", roman: "Joron ka dard, garmi se aaram",
        remedies: [{rem:"rhus_tox",grade:3},{rem:"arsenicum",grade:2},{rem:"causticum",grade:2}] },
      "extremities_swelling": { ur: "سوجن، ہاتھ پاؤں", en: "Swelling, extremities", roman: "Soojan, haath paon",
        remedies: [{rem:"apis",grade:3},{rem:"arsenicum",grade:2},{rem:"rhus_tox",grade:2},{rem:"bryonia",grade:2}] },
      "extremities_cold": { ur: "ہاتھ پاؤں ٹھنڈے", en: "Coldness, hands and feet", roman: "Haath paon thande",
        remedies: [{rem:"calc_carb",grade:3},{rem:"silicea",grade:3},{rem:"sepia",grade:3},{rem:"carbo_veg",grade:2},{rem:"nux_vomica",grade:2}] }
    }
  },
  "generalities": {
    ur: "عمومی علامات", en: "Generalities", roman: "Umomi Alamaat",
    rubrics: {
      "gen_weakness": { ur: "کمزوری", en: "Weakness", roman: "Kamzori",
        remedies: [{rem:"china",grade:3},{rem:"arsenicum",grade:3},{rem:"gelsemium",grade:3},{rem:"phosphorus",grade:2},{rem:"veratrum_alb",grade:2},{rem:"picric_acid",grade:3}] },
      "gen_cold_sensitive": { ur: "سردی کی حساسیت", en: "Cold, sensitive to", roman: "Sardi ki hasasiyat",
        remedies: [{rem:"silicea",grade:3},{rem:"calc_carb",grade:3},{rem:"hepar_sulph",grade:3},{rem:"psorinum",grade:3},{rem:"nux_vomica",grade:2}] },
      "gen_heat_sensitive": { ur: "گرمی کی حساسیت", en: "Heat, sensitive to", roman: "Garmi ki hasasiyat",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"iodum",grade:3},{rem:"apis",grade:3},{rem:"sulphur",grade:3},{rem:"lachesis",grade:2}] },
      "gen_motion_agg": { ur: "حرکت سے بڑھنا", en: "Motion aggravates", roman: "Harkat se barhna",
        remedies: [{rem:"bryonia",grade:3},{rem:"belladonna",grade:2},{rem:"arsenicum",grade:2},{rem:"nux_vomica",grade:2}] },
      "gen_motion_amel": { ur: "حرکت سے آرام", en: "Motion ameliorates", roman: "Harkat se aaram",
        remedies: [{rem:"rhus_tox",grade:3},{rem:"pulsatilla",grade:2},{rem:"ferrum_met",grade:2}] },
      "gen_open_air_desires": { ur: "کھلی ہوا کی خواہش", en: "Open air, desires", roman: "Khuli hawa ki khwahish",
        remedies: [{rem:"pulsatilla",grade:3},{rem:"aconite",grade:2},{rem:"apis",grade:2},{rem:"ignatia",grade:2}] },
      "gen_wet_weather_agg": { ur: "گیلے موسم سے بڑھنا", en: "Wet weather aggravates", roman: "Geelay mausam se barhna",
        remedies: [{rem:"dulcamara",grade:3},{rem:"rhus_tox",grade:3},{rem:"natrum_sulph",grade:3},{rem:"calc_carb",grade:2}] },
      "gen_side_right": { ur: "دائیں طرف کی علامات", en: "Right side complaints", roman: "Dayen taraf ki alamat",
        remedies: [{rem:"lycopodium",grade:3},{rem:"belladonna",grade:2},{rem:"bryonia",grade:2},{rem:"chelidonium",grade:2},{rem:"sanguinaria",grade:2}] },
      "gen_side_left": { ur: "بائیں طرف کی علامات", en: "Left side complaints", roman: "Bayen taraf ki alamat",
        remedies: [{rem:"lachesis",grade:3},{rem:"sulphur",grade:2},{rem:"spigelia",grade:2},{rem:"phosphorus",grade:2}] },
      "gen_sleep_after_agg": { ur: "سونے کے بعد بڑھنا", en: "After sleep aggravates", roman: "Sonay ke baad barhna",
        remedies: [{rem:"lachesis",grade:3},{rem:"nux_vomica",grade:2},{rem:"sulphur",grade:2},{rem:"graphites",grade:2}] }
    }
  }
};

// ==========================================
// REMEDIES DATABASE (Materia Medica Keynotes)
// ==========================================
var REMEDIES_DB_KENT = {
  "aconite": { ur:"ایکونائٹ", en:"Aconitum Napellus", abbr:"Acon.",
    keynotes: { ur:"اچانک شروع، شدید، بے چینی، موت کا خوف۔ ٹھنڈی ہوا سے۔", en:"Sudden onset, intense, anxiety, fear of death. From cold dry wind." },
    worse:"dry_cold_wind,night,warm_room", better:"open_air,rest",
    sphere:"mind,fever,respiratory", potency:"30C / 200C-1M" },
  "belladonna": { ur:"بیلاڈونا", en:"Belladonna", abbr:"Bell.",
    keynotes: { ur:"سرخ چہرہ، دھڑکنے والا درد، گرمی۔ روشنی اور شور سے بڑھے۔", en:"Red face, throbbing pain, heat. Worse light, noise." },
    worse:"light,noise,jar,touch", better:"semi_erect,rest,dark_room",
    sphere:"head,fever,throat", potency:"30C / 200C" },
  "nux_vomica": { ur:"نکس وامیکا", en:"Nux Vomica", abbr:"Nux-v.",
    keynotes: { ur:"چڑچڑاپن، صبح بڑھنا۔ کافی، شراب، مصالحے سے بڑھنا۔", en:"Irritable, worse morning. Worse coffee, alcohol, spices." },
    worse:"morning,cold,open_air,coffee,spices", better:"warmth,rest,evening",
    sphere:"digestive,nervous,sleep,head", potency:"30C / 200C-1M" },
  "bryonia": { ur:"برایونیا", en:"Bryonia Alba", abbr:"Bry.",
    keynotes: { ur:"خشک درد، حرکت سے بڑھنا، آرام سے آرام۔ بہت پیاس۔", en:"Dry pains, worse motion, better rest. Great thirst." },
    worse:"motion,warmth,morning", better:"rest,pressure,cold",
    sphere:"respiratory,joints,head", potency:"30C / 200C-1M" },
  "arsenicum": { ur:"آرسینکم", en:"Arsenicum Album", abbr:"Ars.",
    keynotes: { ur:"بے چینی، جلن، تھوڑا تھوڑا پانی۔ ٹھنڈ سے بڑھنا، گرمی سے آرام۔", en:"Anxiety, burning, sips water. Worse cold, better warmth." },
    worse:"midnight,cold,motion", better:"warmth,warm_drinks",
    sphere:"mind,digestive,respiratory,fever", potency:"30C / 200C-1M" },
  "pulsatilla": { ur:"پلسیٹیلا", en:"Pulsatilla Nigricans", abbr:"Puls.",
    keynotes: { ur:"نرم مزاج، رونا، تسلی سے آرام۔ گرم کمرے میں بڑھنا۔ پیاس نہیں۔", en:"Mild, weepy, consolation amel. Worse warm room. Thirstless." },
    worse:"warm_room,evening,fatty_food", better:"open_air,cold,motion",
    sphere:"mind,female,digestive,respiratory", potency:"30C / 200C" },
  "rhus_tox": { ur:"رس ٹاکس", en:"Rhus Toxicodendron", abbr:"Rhus-t.",
    keynotes: { ur:"جوڑوں کا درد، حرکت سے آرام۔ ٹھنڈے گیلے موسم سے بڑھنا۔", en:"Joint pain, continued motion amel. Worse cold wet weather." },
    worse:"cold_wet,rest,night,first_motion", better:"continued_motion,warmth,dry_weather",
    sphere:"joints,skin,fever,back", potency:"30C / 200C" },
  "lycopodium": { ur:"لائیکوپوڈیم", en:"Lycopodium", abbr:"Lyc.",
    keynotes: { ur:"شام 4-8 بجے بڑھنا۔ ریاح۔ دائیں طرف۔ میٹھے کی خواہش۔", en:"Worse 4-8 PM. Flatulence. Right-sided. Desires sweets." },
    worse:"4_8_pm,warm_room", better:"open_air,cold_drinks,motion",
    sphere:"digestive,urinary,head", potency:"30C / 200C-1M" },
  "phosphorus": { ur:"فاسفورس", en:"Phosphorus", abbr:"Phos.",
    keynotes: { ur:"خون بہنا، جلن۔ ٹھنڈا پانی چاہیے جو گرم ہو کر قے میں آئے۔", en:"Bleeding, burning. Cold water desired, vomited when warm." },
    worse:"evening,thunderstorm,lying_left", better:"cold,sleep,eating",
    sphere:"respiratory,bleeding,nervous", potency:"30C / 200C" },
  "sulphur": { ur:"سلفر", en:"Sulphur", abbr:"Sulph.",
    keynotes: { ur:"جلن، گرمی، بدبو۔ نہانے سے بڑھنا۔ پاؤں میں جلن۔ صبح 11 بجے کمزوری۔", en:"Burning, heat, offensive. Worse bathing. Burning feet. 11 AM weak." },
    worse:"11_am,warmth_of_bed,bathing,standing", better:"dry_warm_weather",
    sphere:"skin,digestive,sleep", potency:"30C / 200C-1M" },
  "china": { ur:"چائنا", en:"China Officinalis", abbr:"Chin.",
    keynotes: { ur:"کمزوری، خون کی کمی۔ پیٹ پھولنا۔ بھوک مگر جلدی پیٹ بھرنا۔", en:"Weakness, anemia. Flatulence. Hungry yet easily satiated." },
    worse:"night,eating,loss_of_fluids", better:"hard_pressure,warmth",
    sphere:"digestive,fever,weakness", potency:"30C / 200C" },
  "ignatia": { ur:"اگنیشیا", en:"Ignatia Amara", abbr:"Ign.",
    keynotes: { ur:"غم، صدمے سے۔ متضاد علامات۔ گلے میں گولا۔ آہ بھرنا۔", en:"Grief, shock. Contradictory symptoms. Lump in throat. Sighing." },
    worse:"grief,fright,morning,open_air,coffee", better:"eating,swallowing",
    sphere:"mind,throat,female", potency:"30C / 200C" },
  "natrum_mur": { ur:"نیٹرم میور", en:"Natrum Muriaticum", abbr:"Nat-m.",
    keynotes: { ur:"اداسی، تنہائی، تسلی سے بڑھنا۔ نمکین کی خواہش۔ صبح سر درد۔", en:"Sad, solitary, worse consolation. Desires salt. Morning headache." },
    worse:"morning,consolation,sun", better:"open_air,cold_bathing",
    sphere:"mind,head,female,skin", potency:"30C / 200C-1M" },
  "sepia": { ur:"سیپیا", en:"Sepia Officinalis", abbr:"Sep.",
    keynotes: { ur:"بے حسی، تھکاوٹ۔ ہر کام سے نفرت۔ چاندی پر درد۔ حیض سے پہلے بڑھنا۔", en:"Indifference, fatigue. Aversion to everything. Vertex pain." },
    worse:"morning,evening,before_menses", better:"exercise,warmth,sleep",
    sphere:"female,mind,skin,head", potency:"30C / 200C-1M" },
  "lachesis": { ur:"لیکیسس", en:"Lachesis Muta", abbr:"Lach.",
    keynotes: { ur:"بائیں طرف۔ سونے کے بعد بڑھنا۔ تنگ کپڑے برداشت نہیں۔", en:"Left-sided. Worse after sleep. Cannot bear tight clothing." },
    worse:"after_sleep,tight_clothing,spring", better:"discharges,open_air",
    sphere:"female,throat,mind", potency:"30C / 200C-1M" },
  "gelsemium": { ur:"جیلسیمیم", en:"Gelsemium", abbr:"Gels.",
    keynotes: { ur:"کمزوری، کپکپی، بھاری پن۔ بری خبر سے۔ امتحان کا ڈر۔ گدی میں سر درد۔", en:"Weakness, trembling. From bad news. Exam fear. Occipital headache." },
    worse:"bad_news,anticipation,summer", better:"urination,open_air",
    sphere:"mind,head,fever", potency:"30C / 200C" },
  "chamomilla": { ur:"کیموملا", en:"Chamomilla", abbr:"Cham.",
    keynotes: { ur:"بہت چڑچڑا، کچھ برداشت نہیں۔ بچوں کے دانت کا درد۔", en:"Extremely irritable. Teething pain in children." },
    worse:"anger,night,coffee,heat,teething", better:"carrying,cold_applications",
    sphere:"mind,children,teeth,ears", potency:"30C / 200C" },
  "mercurius": { ur:"مرکیوریس", en:"Mercurius Solubilis", abbr:"Merc.",
    keynotes: { ur:"بدبودار منہ، لعاب زیادہ۔ رات کو بڑھنا۔ پسینہ بے آرام۔", en:"Offensive mouth, excess saliva. Worse night. Sweat without relief." },
    worse:"night,damp,cold_air,sweating", better:"rest,morning",
    sphere:"mouth,throat,skin,glands", potency:"30C / 200C" },
  "ipecac": { ur:"اپیکیاک", en:"Ipecacuanha", abbr:"Ip.",
    keynotes: { ur:"مسلسل متلی، قے سے آرام نہیں۔ صاف زبان۔ بلغم والی کھانسی۔", en:"Persistent nausea. Clean tongue. Rattling cough." },
    worse:"warm_room,winter,lying", better:"open_air,rest",
    sphere:"stomach,respiratory", potency:"30C / 200C" },
  "apis": { ur:"ایپس", en:"Apis Mellifica", abbr:"Apis.",
    keynotes: { ur:"سوجن، چبھنے والا درد۔ گرمی سے بڑھنا، ٹھنڈ سے آرام۔ پیاس نہیں۔", en:"Swelling, stinging pain. Worse heat, better cold. Thirstless." },
    worse:"heat,touch,afternoon", better:"cold_applications,open_air",
    sphere:"skin,urinary,joints", potency:"30C / 200C" },
  "calc_carb": { ur:"کیلکیریا کارب", en:"Calcarea Carbonica", abbr:"Calc.",
    keynotes: { ur:"موٹے، سست، ٹھنڈ پسند۔ سر پر پسینہ۔ انڈے، مٹی کی خواہش۔", en:"Fat, sluggish, chilly. Sweat on head. Desires eggs." },
    worse:"cold,exertion,morning", better:"dry_weather,lying",
    sphere:"children,bones,glands", potency:"200C / 1M" },
  "silicea": { ur:"سلیشیا", en:"Silicea Terra", abbr:"Sil.",
    keynotes: { ur:"سردی کی حساسیت، کمزوری، اعتماد کی کمی۔ پیپ کا اخراج۔", en:"Chilly, weak, no confidence. Pus formation." },
    worse:"cold,winter,morning", better:"warmth,summer",
    sphere:"skin,nails,glands,bones", potency:"30C / 200C-1M" },
  "hepar_sulph": { ur:"ہیپر سلف", en:"Hepar Sulphuris", abbr:"Hep.",
    keynotes: { ur:"سردی سے بہت حساس۔ پیپ، بدبو۔ تھوڑی سی سردی سے چھینکیں۔", en:"Extremely chilly. Pus, offensive. Sneezes from least cold." },
    worse:"cold_air,uncovering,night", better:"warmth,damp_weather",
    sphere:"respiratory,skin,throat", potency:"30C / 200C" },
  "colocynth": { ur:"کولوسنتھس", en:"Colocynthis", abbr:"Coloc.",
    keynotes: { ur:"مروڑ والا پیٹ درد، دباؤ سے آرام۔ غصے سے بڑھنا۔", en:"Cramping pain, better pressure. Worse anger." },
    worse:"anger,eating,night", better:"pressure,bending_double,warmth",
    sphere:"abdomen,nervous", potency:"30C / 200C" },
  "carbo_veg": { ur:"کاربو ویج", en:"Carbo Vegetabilis", abbr:"Carb-v.",
    keynotes: { ur:"شدید کمزوری، ٹھنڈی جلد مگر پنکھا چاہیے۔ ریاح، ڈکار۔", en:"Extreme weakness, cold skin yet wants fanning. Flatulence." },
    worse:"evening,warmth,fatty_food", better:"fanning,cold_air,belching",
    sphere:"digestive,circulation", potency:"30C / 200C" },
  "veratrum_alb": { ur:"ویرٹرم البم", en:"Veratrum Album", abbr:"Verat.",
    keynotes: { ur:"شدید کمزوری، ٹھنڈا پسینہ، قے اور دست۔ کھٹائی کی خواہش۔", en:"Extreme weakness, cold sweat. Desires sour." },
    worse:"drinking,exertion,night", better:"warmth,lying",
    sphere:"stomach,weakness", potency:"30C / 200C" },
  "dulcamara": { ur:"ڈلکامارا", en:"Dulcamara", abbr:"Dulc.",
    keynotes: { ur:"گیلے موسم، بارش سے بڑھنا۔ سردی لگ کر بخار۔", en:"Worse wet weather, rain. Fever from catching cold." },
    worse:"wet_weather,rain,cold", better:"motion,dry_weather",
    sphere:"respiratory,joints,skin", potency:"30C / 200C" },
  "staphysagria": { ur:"اسٹیفسیگریا", en:"Staphysagria", abbr:"Staph.",
    keynotes: { ur:"دبا ہوا غصہ، بے عزتی سے۔ جسمانی اور ذہنی صدمے۔", en:"Suppressed anger, from indignation. Physical and mental shocks." },
    worse:"anger,indignation,touch,morning", better:"warmth,rest,breakfast",
    sphere:"mind,urinary,skin", potency:"30C / 200C-1M" },
  "glonoine": { ur:"گلونوئن", en:"Glonoinum", abbr:"Glon.",
    keynotes: { ur:"دھوپ سے سر درد، دھڑکنے والا۔ سر میں خون کا بہاؤ۔", en:"Sun headache, throbbing. Rush of blood to head." },
    worse:"sun,jar,lying_down,heat", better:"uncovering,cold,sitting_up",
    sphere:"head,fever", potency:"30C / 200C" },
  "argentum_nit": { ur:"آرجینٹم نائٹ", en:"Argentum Nitricum", abbr:"Arg-n.",
    keynotes: { ur:"جلد بازی، وقت آہستہ گزرتا ہے۔ امتحان کا ڈر۔ میٹھے کی خواہش۔", en:"Hasty, time passes slowly. Exam fear. Desires sweets." },
    worse:"anticipation,warmth,night,sweets", better:"cold_air,burping",
    sphere:"mind,throat,digestive", potency:"30C / 200C" }
};

console.log("✅ Repertory Data: " + Object.keys(REPERTORY_DATA).length + " chapters, " +
  Object.values(REPERTORY_DATA).reduce(function(s,ch){return s+Object.keys(ch.rubrics).length;},0) + " rubrics, " +
  Object.keys(REMEDIES_DB_KENT).length + " remedies");
