// v78: layout/data separation — split files load in order, header tabs, tools moved to Settings, diff tab groups
const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'..');
let fails=0;const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)fails++;};
const idx=fs.readFileSync(ROOT+'/index.html','utf8');
const order=fs.readFileSync(ROOT+'/js/repertory/LOAD_ORDER.txt','utf8').split(/\s+/).filter(Boolean);
ok(order.length===10&&order.every(f=>fs.existsSync(ROOT+'/js/repertory/'+f)),'10 repertory JS parts exist');
let last=-1,inOrder=true;order.forEach(f=>{const i=idx.indexOf('js/repertory/'+f);if(i<=last)inOrder=false;last=i;});
ok(inOrder&&idx.indexOf('js/repertory/rep-analysis.js')<idx.indexOf('js/08b-rep-differentiation.js'),'index.html loads parts in LOAD_ORDER, before 08b');
ok(!/08-app-repertory\.js|css\/style\.css/.test(idx),'old monolithic files no longer referenced');
const css=['app','repertory','differentiation','repertory-tree','library','layout-header','layout-repertory-toolbar','layout-differentiation'];
last=-1;inOrder=true;css.forEach(n=>{const i=idx.indexOf('css/'+n+'.css');if(i<=last)inOrder=false;last=i;});ok(inOrder,'CSS files linked in cascade order');
const nav=idx.slice(idx.indexOf('<nav class="nav-bar">'),idx.indexOf('</nav>'));
ok((nav.match(/data-page=/g)||[]).length===7&&!/navHelpBtn|navTourBtn|navPrefsBtn|navTipBtn/.test(nav),'main nav = 7 page tabs only (v79: All Patients tab removed — dashboard All-Time list covers it)');
ok(!/data-page="allPatients"/.test(nav)&&nav.indexOf('data-page="settings"')>nav.indexOf('data-page="repertoryBrowser"')&&nav.indexOf('data-page="repertoryBrowser"')>nav.indexOf('data-page="diagnosis"'),'v79: Settings last after Repertory, All Patients tab gone');
const set=idx.slice(idx.indexOf('id="page-settings"'));
ok(['navPrefsBtn','navHelpBtn','navTourBtn','navTipBtn'].every(id=>set.indexOf('id="'+id+'"')>0),'Preferences/Help/Tour/Tip live in Settings (same ids)');
const sw=fs.readFileSync(ROOT+'/service-worker.js','utf8');
ok(order.every(f=>sw.includes('./js/repertory/'+f))&&css.every(n=>sw.includes('./css/'+n+'.css')),'service worker caches every split file');
const d=fs.readFileSync(ROOT+'/js/08b-rep-differentiation.js','utf8');
ok(/rep-diff-tabgrp/.test(d)&&d.indexOf("tab('rubric'")<d.indexOf("tab('excl'"),'diff tabs grouped (Analysis → Evidence), rubric comparison first');
console.log(fails?'FAILURES: '+fails:'ALL v78 LAYOUT CHECKS PASSED');process.exit(fails?1:0);
